// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"0ada899958fb005672dcb7cf7cade0a39be5ffc22d30082081076ad1384ed3f812e8c7c26ef0dae15c73033e47f7632d8e379034450a959d7fcae9c5fb646525164fd8a1fb40cdb796230e461c4f4fbcf75e894a0d9a19d82690935f165d497c04a964a3ff7de02dc3bf953b7ff09120e7e07329b216fd5e4adbdb1956bf0d20208fda63ac51f9b93655aded4aec955dec82d90bf555d70068f6fd13d57b4ec304bcd775b759820982650fdf515ba794e79a61287dfb27526007bf889ee7d3c12a6c893c2b5ac52042e2a903125f75ab7bdc76bdc2e5a14bf6e7b5883e4db9ad2dcd5dae97936530016098032f94bacaacd61040f102db44cc0f31efb4516b1b";
    bytes32 public constant POST_DIGEST = bytes32(0xc799203f040ca28956c6be56ff8aa97d43250caead998325ba004fcb5a6e7c91);
    bytes public constant JOURNAL =
        hex"5818100a2105c60d4f73044fe09a9cb0ba9801a4f5775e79cbb8934b23caab65fc78119308df16cf37c04f2bc4fca8e041425d654ce274515bbdfbea1f9070f000000001c48217f74c7707ba564c32cd3db0abcd2057a41e00000001ed28d58ebad0ccb2bccf71425d785388b9914029";
    bytes32 public constant IMAGE_ID = bytes32(0x88c105ee779cd8562cda0a2e0eb5d652a640ca0fd47bf8653f0705acf2ea373c);
}
