// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"0b79052f45ac3c4873607632575e2f8777ee1776e702eb09c419487a80228fd51ae4c3bec6344ddcc9c31f180ea571326102d5f640e2f2a17dec9f608007e63802f4c00951d50a256afc2fb6829d3679748b5ea57931bf6921ab07a7492ca3751fddf7493b473b6f99c3c036004f9f1c0d985fb00cbd6d64d4ddb5cabafd49fc29c7ac262d12fc190522384f0b77b3139fcc51516eefc088a6bc49093b28029827d7612bff120f2880eab4b7bb1aa1cdaa563193827f01119f8e57cef6daf6a516d8c0445ea5f5514fdbe9e3a1e2b6d4cc4ac7983982bbc8cffee7a9177032a32382aadee5f7017ab25b2a7c82b355d46e7c9cbe13587d552cebd14a816b448e";
    bytes32 public constant POST_DIGEST = bytes32(0xb8e6dde26b99d84dd257eef56a4f9adc1b03a0bb88ca5a3ad39a91e367f5c3f7);
    bytes public constant JOURNAL = hex"";
    bytes32 public constant IMAGE_ID = bytes32(0x35e14f92e1c7989a467611bb39d2cf7f46dc4488404f8e8179960cc7be13f8a8);
}
