// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by:
// cargo xtask bootstrap-groth16

pragma solidity ^0.8.13;

library TestReceipt {
    bytes public constant SEAL =
        hex"13c5374cbe30ae3a9e292ddaa04e4b17a033fbf16c20169ca7e8ea7e893317161eeb54246b11f5f731144543a5fdd384616fd06a72b851f9a5701a6d983469b90af561d4397deeca0264031f56d99c3ca224c31f59c5c50f80e0bb62c6bd28331a2a42156c883f9fcf197cd79d5c5d032d94fe5ccbe53dcf4a0b74a219c18ac71e9c0d476910e93fde55b6ec8e1b52c5e5f0a2110747e7c9fa257422d686b88617dd034c1d329efceaca91a87a4051f439098a2bfc0f7e466160b38a590a63d20d9ecda0df1b8ab7305ef509cc8dfbc6bbc6b5f82db20128b3c8d207838787a11943525ea3d27c503638890893872df5e012454e1e62c73e9a60eec09e504dd1";
    bytes32 public constant POST_DIGEST = bytes32(0xdd9c6194587a2e082edf9b7086c5fc4555958668a4f6774243b921e6dade84a0);
    bytes public constant JOURNAL = hex"";
    bytes32 public constant IMAGE_ID = bytes32(0x950df86e2dc6df7d98f4d2fd5468b30986721f87ef228b39f39d740fcbf5ac34);
}
