// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SemanticVersion {
    #[prost(uint64, tag = "1")]
    pub major: u64,
    #[prost(uint64, tag = "2")]
    pub minor: u64,
    #[prost(uint64, tag = "3")]
    pub patch: u64,
    #[prost(string, tag = "4")]
    pub pre: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub build: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CompatVersion {
    #[prost(uint32, tag = "1")]
    pub value: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Digest {
    #[prost(uint32, repeated, tag = "1")]
    pub words: ::prost::alloc::vec::Vec<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ExitCode {
    #[prost(oneof = "exit_code::Kind", tags = "1, 2, 3, 4")]
    pub kind: ::core::option::Option<exit_code::Kind>,
}
/// Nested message and enum types in `ExitCode`.
pub mod exit_code {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Kind {
        #[prost(uint32, tag = "1")]
        Halted(u32),
        #[prost(uint32, tag = "2")]
        Paused(u32),
        #[prost(message, tag = "3")]
        SystemSplit(()),
        #[prost(message, tag = "4")]
        SessionLimit(()),
    }
}
