// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/// EVM bytecode configuration

use serde::{Deserialize, Serialize};
use crate::abi::abi_encode;

// Include the auto-generated bytecode
include!(concat!(env!("OUT_DIR"), "/contract_bytecode.rs"));

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct EvmConfig {
    pub bytecode: Vec<u8>,
    pub calldata: Vec<u8>,
}

impl Default for EvmConfig {
    fn default() -> Self {
        Self {
            // Bytecode compiled from Contract.sol at build time
            bytecode: hex::decode(CONTRACT_BYTECODE).unwrap(),
            calldata: abi_encode("isSolved(int256)", 42),
        }
    }
}

impl EvmConfig {
    /// Create a new EVM config with custom bytecode
    pub fn new(bytecode_hex: &str, calldata: Vec<u8>) -> Result<Self, hex::FromHexError> {
        let bytecode = hex::decode(bytecode_hex)?;
        Ok(Self { bytecode, calldata })
    }
    
    /// Get the bytecode as a reference
    pub fn get_bytecode(&self) -> &[u8] {
        &self.bytecode
    }
    
    /// Get the bytecode as owned Vec
    pub fn get_bytecode_owned(&self) -> Vec<u8> {
        self.bytecode.clone()
    }

    /// Get the calldata
    pub fn get_calldata(&self) -> &[u8] {
        &self.calldata
    }
}
