// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

use super::super::verify::CircuitInfo;
use risc0_zkp::{
    adapter::TapsProvider,
    taps::{TapData, TapSet},
};

pub const TAPSET: &TapSet = &TapSet::<'static> {
    taps: &[
        TapData {
            offset: 0,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 1,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 2,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 3,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 4,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 5,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 6,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 7,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 8,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 9,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 10,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 11,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 12,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 13,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 14,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 15,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 16,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 17,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 18,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 19,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 20,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 21,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 22,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 23,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 24,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 25,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 26,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 27,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 28,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 29,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 30,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 31,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 32,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 33,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 34,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 35,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 36,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 37,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 38,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 39,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 40,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 41,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 42,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 43,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 44,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 45,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 46,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 47,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 48,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 49,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 50,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 51,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 52,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 53,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 54,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 55,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 56,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 57,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 58,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 59,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 60,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 61,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 62,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 63,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 64,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 65,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 66,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 67,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 68,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 69,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 70,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 71,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 72,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 73,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 74,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 75,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 76,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 77,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 78,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 79,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 80,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 81,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 82,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 83,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 84,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 85,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 86,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 87,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 88,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 89,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 90,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 91,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 92,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 93,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 94,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 95,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 96,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 97,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 98,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 99,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 100,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 101,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 102,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 103,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 104,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 105,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 106,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 107,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 108,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 109,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 110,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 111,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 112,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 113,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 114,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 115,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 116,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 117,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 118,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 119,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 120,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 121,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 122,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 123,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 124,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 125,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 126,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 127,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 128,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 129,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 130,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 131,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 132,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 133,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 134,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 135,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 136,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 137,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 138,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 139,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 140,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 141,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 142,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 143,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 144,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 145,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 146,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 147,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 148,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 149,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 150,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 151,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 152,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 153,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 154,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 155,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 156,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 157,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 158,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 159,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 160,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 161,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 162,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 163,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 164,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 165,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 166,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 167,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 168,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 169,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 170,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 171,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 172,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 173,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 174,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 175,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 176,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 177,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 178,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 179,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 180,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 181,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 182,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 183,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 184,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 185,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 186,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 187,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 188,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 189,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 190,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 191,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 192,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 193,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 194,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 195,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 196,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 197,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 198,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 0,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 0,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 1,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 1,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 2,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 2,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 3,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 3,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 4,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 5,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 6,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 7,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 8,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 9,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 10,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 11,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 12,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 13,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 14,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 15,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 16,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 17,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 18,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 19,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 20,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 21,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 22,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 23,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 24,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 25,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 26,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 27,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 28,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 29,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 30,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 31,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 32,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 33,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 34,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 35,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 36,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 37,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 38,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 39,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 40,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 41,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 42,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 43,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 44,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 45,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 46,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 47,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 48,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 49,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 50,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 51,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 52,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 53,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 54,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 55,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 56,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 57,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 58,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 59,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 60,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 61,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 62,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 63,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 64,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 65,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 66,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 67,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 68,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 69,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 70,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 71,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 72,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 73,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 74,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 75,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 76,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 77,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 78,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 79,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 80,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 81,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 82,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 83,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 84,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 85,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 86,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 87,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 88,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 89,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 90,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 91,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 92,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 93,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 94,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 95,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 96,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 97,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 98,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 99,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 100,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 101,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 102,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 103,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 104,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 105,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 106,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 107,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 108,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 109,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 110,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 111,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 112,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 113,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 114,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 115,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 116,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 117,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 118,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 119,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 120,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 121,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 122,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 123,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 124,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 125,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 126,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 127,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 128,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 129,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 130,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 131,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 132,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 133,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 134,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 135,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 136,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 137,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 138,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 139,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 140,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 141,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 142,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 143,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 144,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 145,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 146,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 147,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 148,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 149,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 150,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 151,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 152,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 153,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 154,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 155,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 156,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 156,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 157,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 157,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 158,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 158,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 159,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 159,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 160,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 160,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 161,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 161,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 162,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 162,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 163,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 163,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 164,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 164,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 165,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 165,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 166,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 166,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 167,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 167,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 168,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 168,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 169,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 169,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 170,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 170,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 171,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 171,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 172,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 172,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 173,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 173,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 174,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 174,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 175,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 175,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 176,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 176,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 177,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 177,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 178,
            back: 0,
            group: 1,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 178,
            back: 1,
            group: 1,
            combo: 1,
            skip: 2,
        },
    ],
    combo_taps: &[0, 0, 1],
    combo_begin: &[0, 1, 3],
    group_begin: &[0, 199, 405],
    combos_count: 2,
    reg_count: 378,
    tot_combo_backs: 3,
    group_names: &["data", "accum"],
};

impl TapsProvider for CircuitInfo {
    fn get_taps(&self) -> &'static TapSet<'static> {
        TAPSET
    }
}
