// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is automatically generated.

use risc0_zkp::core::digest::Digest;
use risc0_zkp::digest;

pub const KECCAK_CONTROL_ID: Digest =
    digest!("0d1c2772c28cca62aa8568112406502d1d7c3241cbc6d9442159c60f73451560");

pub const KECCAK_CONTROL_ROOT: Digest =
    digest!("125fbb2d94fa6e033e55a7538e082029be45324b884e543d3859f3549fef174a");
