// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated.

use risc0_zkp::core::digest::Digest;
use risc0_zkp::digest;

pub const KECCAK_CONTROL_IDS: &[Digest] = &[
    digest!("92631f2b8dc9431cb2abdc1e82ac2e30deaf086a36e51e4aa60ad0516bf5b748"), // keccak_lift po2=14
    digest!("cacefc600b59de2dbb280764f448dc2b6c6fb557fb05800aedd66237b2838c60"), // keccak_lift po2=15
    digest!("8120201571ad74095087207325b3251d97b3d3391e897922a6cf2f3f3693e850"), // keccak_lift po2=16
    digest!("1211351795b7710d6b936e50a5ecc51ae556b07385dc854539b7da2732dba16f"), // keccak_lift po2=17
    digest!("41db96728251e1740ee3471a400f2a3ce6108d0f889ecd5094005577f8502a34"), // keccak_lift po2=18
];

pub const KECCAK_CONTROL_ROOT: Digest =
    digest!("7bd95f35f83ad259c16020210f036058e9d7f9725c8ef628f8b6770cde3d176a");
