// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// This file is automatically generated.

use risc0_zkp::core::digest::Digest;
use risc0_zkp::digest;

pub const KECCAK_CONTROL_IDS: &[Digest] = &[
    digest!("ac7c6d4c45958431995be877143b4820348172384d2ee8568e627819989ad16c"), // keccak_lift po2=14
    digest!("3bdc374b1b517c41447db21face8883804c92730fa1de5746217174b33adea32"), // keccak_lift po2=15
    digest!("aa86474afc64141ec0fc50722cf10e233526b3454e80fc49657adb1db247c320"), // keccak_lift po2=16
    digest!("2efcda7414108e6956eeda3fcfe0c7051b7d880806266830c7fb324ec599dc28"), // keccak_lift po2=17
    digest!("8979d234ace6b26a41a71b353c31ba4ecce17500a851df1ce2357006e0af1206"), // keccak_lift po2=18
];

pub const KECCAK_CONTROL_ROOT: Digest =
    digest!("c4c6721b179b8501218a842a3731e14017f0cc2eaaba2d076f98eb2aa305564f");
