// Copyright 2023 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Warning: this code is generated by cargo xtask and should not be modified by
// hand.

/// The image ID of the fault checker guest program
#[rustfmt::skip]
pub const FAULT_CHECKER_ID: [u32; 8] = [1419758754, 3094564905, 724715785, 1323411806, 812173780, 2092560110, 592399456, 3988838947];

/// The ELF of the fault checker guest program
#[rustfmt::skip]
pub const FAULT_CHECKER_ELF: &[u8] = include_bytes!("fault_checker.elf");
