// Copyright 2024 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Automatically generated by:
//   cargo run -F make_control_ids --bin make_control_ids > zirgen/circuit/bigint/src/control_id.rs
// (Normally run as part of `cargo bootstrap bigint`)

use risc0_zkp::{core::digest::Digest, digest};

pub const RSA_256_X1_CONTROL_ID: Digest =
    digest!("b64d9520da37fe3fb06b5254065d140238bd165a7b41bf51ef3fc25433e98503");
pub const RSA_256_X1_CONTROL_ROOT: Digest =
    digest!("39b42c22d723a56dda3ab641aecbf92442a7ff4415fe800b814a3d086a159e2b");

pub const RSA_256_X2_CONTROL_ID: Digest =
    digest!("c9b17f4d82070833e6d6023304b4111ef1e48767f204d66e705eff2074c28655");
pub const RSA_256_X2_CONTROL_ROOT: Digest =
    digest!("32d34e64a3d70b09ed889d63d9df1c4ffa468b1a150fc31246bc994c73e43b14");

pub const RSA_3072_X15_CONTROL_ID: Digest =
    digest!("5b8c6338762a361b58cdf418544cb321a5b11961e6907e05759a30130f892801");
pub const RSA_3072_X15_CONTROL_ROOT: Digest =
    digest!("a5568767aa62fd111843d721c213910cdad0f03386db8269301f0009efd86041");
