#!/bin/bash

set -euo pipefail

TOOLCHAIN=${BUILDKITE_PLUGIN_RUSTUP_TOOLCHAIN}

if ! command -v rustup &>/dev/null; then
  curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- -y
  export PATH="$HOME/.cargo/bin:$PATH"
fi

rustup override unset
rustup default $TOOLCHAIN
# rustup target add ${{ inputs.targets }}
# rustup component add ${{ inputs.components }}

export CARGO_NET_RETRY=10
export CARGO_TERM_COLOR=always
export RUSTUP_MAX_RETRIES=10

rustup show active-toolchain || rustup toolchain install
rustc --version --verbose
