// Copyright 2025 RISC Zero, Inc.
//
// This project is dual-licensed under either:
// - Apache License, Version 2.0 (LICENSE-APACHE or https://www.apache.org/licenses/LICENSE-2.0)
// - MIT License (LICENSE-MIT or https://opensource.org/licenses/MIT)
// at your option.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This file is automatically generated.

use risc0_zkp::core::digest::Digest;
use risc0_zkp::digest;

pub const KECCAK_CONTROL_IDS: &[Digest] = &[{}];

pub const KECCAK_CONTROL_ROOT: Digest = digest!("{}");
