// Copyright 2025 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0, <LICENSE-APACHE or
// http://apache.org/licenses/LICENSE-2.0> or the MIT license <LICENSE-MIT or
// http://opensource.org/licenses/MIT>, at your option. This file may not be
// copied, modified, or distributed except according to those terms.
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0 OR MIT

// This code is automatically generated

use risc0_zkp::taps::{TapData, TapSet};

#[allow(missing_docs)]
pub const TAPSET: &TapSet = &TapSet::<'static> {
    taps: &[
        TapData {
            offset: 0,
            back: 0,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 0,
            back: 1,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 1,
            back: 0,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 1,
            back: 1,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 2,
            back: 0,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 2,
            back: 1,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 3,
            back: 0,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 3,
            back: 1,
            group: 0,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 4,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 5,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 6,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 7,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 8,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 9,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 10,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 11,
            back: 0,
            group: 0,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 0,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 1,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 2,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 3,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 4,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 5,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 6,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 7,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 8,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 9,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 10,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 11,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 12,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 13,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 14,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 15,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 16,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 17,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 18,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 19,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 20,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 21,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 22,
            back: 0,
            group: 1,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 0,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 0,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 1,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 1,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 2,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 2,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 3,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 3,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 4,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 4,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 5,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 6,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 7,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 8,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 9,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 10,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 11,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 12,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 13,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 14,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 15,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 16,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 17,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 18,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 19,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 20,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 21,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 22,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 23,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 24,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 25,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 26,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 26,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 26,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 26,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 26,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 26,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 27,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 27,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 27,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 27,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 27,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 27,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 28,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 28,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 28,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 28,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 28,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 28,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 29,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 29,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 29,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 29,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 29,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 29,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 30,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 30,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 30,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 30,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 30,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 30,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 31,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 31,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 31,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 31,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 31,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 31,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 32,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 32,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 32,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 32,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 32,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 32,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 33,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 33,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 33,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 33,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 33,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 33,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 34,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 34,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 34,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 34,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 34,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 34,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 35,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 35,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 35,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 35,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 35,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 35,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 36,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 36,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 36,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 36,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 36,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 36,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 37,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 37,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 37,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 37,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 37,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 37,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 38,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 38,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 38,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 38,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 38,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 38,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 39,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 39,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 39,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 39,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 39,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 39,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 40,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 40,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 40,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 40,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 40,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 40,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 41,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 41,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 41,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 41,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 41,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 41,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 42,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 42,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 42,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 42,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 42,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 42,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 43,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 43,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 43,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 43,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 43,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 43,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 44,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 44,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 44,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 44,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 44,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 44,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 45,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 45,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 45,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 45,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 45,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 45,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 46,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 46,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 46,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 46,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 46,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 46,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 47,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 47,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 47,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 47,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 47,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 47,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 48,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 48,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 48,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 48,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 48,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 48,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 49,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 49,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 49,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 49,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 49,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 49,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 50,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 50,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 50,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 50,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 50,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 50,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 51,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 51,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 51,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 51,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 51,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 51,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 52,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 52,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 52,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 52,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 52,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 52,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 53,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 53,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 53,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 53,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 53,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 53,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 54,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 54,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 54,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 54,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 54,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 54,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 55,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 55,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 55,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 55,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 55,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 55,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 56,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 56,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 56,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 56,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 56,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 56,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 57,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 57,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 57,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 57,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 57,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 57,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 58,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 59,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 60,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 60,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 60,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 60,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 60,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 60,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 61,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 61,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 61,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 61,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 61,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 61,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 62,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 62,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 62,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 62,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 62,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 62,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 63,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 63,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 63,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 63,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 63,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 63,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 64,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 64,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 64,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 64,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 64,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 64,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 65,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 65,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 65,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 65,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 65,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 65,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 66,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 66,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 66,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 66,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 66,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 66,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 67,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 67,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 67,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 67,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 67,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 67,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 68,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 68,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 68,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 68,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 68,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 68,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 69,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 69,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 69,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 69,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 69,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 69,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 70,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 70,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 70,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 70,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 70,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 70,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 71,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 71,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 71,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 71,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 71,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 71,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 72,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 72,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 72,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 72,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 72,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 72,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 73,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 73,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 73,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 73,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 73,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 73,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 74,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 74,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 74,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 74,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 74,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 74,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 75,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 75,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 75,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 75,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 75,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 75,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 76,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 76,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 76,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 76,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 76,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 76,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 77,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 77,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 77,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 77,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 77,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 77,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 78,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 78,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 78,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 78,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 78,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 78,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 79,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 79,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 79,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 79,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 79,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 79,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 80,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 80,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 80,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 80,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 80,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 80,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 81,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 81,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 81,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 81,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 81,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 81,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 82,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 82,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 82,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 82,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 82,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 82,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 83,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 83,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 83,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 83,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 83,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 83,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 84,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 84,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 84,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 84,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 84,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 84,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 85,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 85,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 85,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 85,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 85,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 85,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 86,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 86,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 86,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 86,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 86,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 86,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 87,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 87,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 87,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 87,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 87,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 87,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 88,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 88,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 88,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 88,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 88,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 88,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 89,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 89,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 89,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 89,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 89,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 89,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 90,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 90,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 90,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 90,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 90,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 90,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 91,
            back: 0,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 91,
            back: 1,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 91,
            back: 2,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 91,
            back: 3,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 91,
            back: 4,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 91,
            back: 68,
            group: 2,
            combo: 2,
            skip: 6,
        },
        TapData {
            offset: 92,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 92,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 93,
            back: 0,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 93,
            back: 1,
            group: 2,
            combo: 1,
            skip: 2,
        },
        TapData {
            offset: 94,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 94,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 94,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 94,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 94,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 94,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 95,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 95,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 95,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 95,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 95,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 95,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 96,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 96,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 96,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 96,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 96,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 96,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 97,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 97,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 97,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 97,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 97,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 97,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 98,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 98,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 98,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 98,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 98,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 98,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 99,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 99,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 99,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 99,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 99,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 99,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 100,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 100,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 100,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 100,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 100,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 100,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 101,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 101,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 101,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 101,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 101,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 101,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 102,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 102,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 102,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 102,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 102,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 102,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 103,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 103,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 103,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 103,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 103,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 103,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 104,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 104,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 104,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 104,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 104,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 104,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 105,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 105,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 105,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 105,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 105,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 105,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 106,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 106,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 106,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 106,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 106,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 106,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 107,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 107,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 107,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 107,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 107,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 107,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 108,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 108,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 108,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 108,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 108,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 108,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 109,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 109,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 109,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 109,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 109,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 109,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 110,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 110,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 110,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 110,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 110,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 110,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 111,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 111,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 111,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 111,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 111,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 111,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 112,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 112,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 112,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 112,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 112,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 112,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 113,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 113,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 113,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 113,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 113,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 113,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 114,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 114,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 114,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 114,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 114,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 115,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 115,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 115,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 115,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 115,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 116,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 116,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 116,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 116,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 116,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 117,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 117,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 117,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 117,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 117,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 118,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 118,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 118,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 118,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 118,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 119,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 119,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 119,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 119,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 119,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 120,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 120,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 120,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 120,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 120,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 121,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 121,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 121,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 121,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 121,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 122,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 122,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 122,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 122,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 122,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 123,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 123,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 123,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 123,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 123,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 124,
            back: 0,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 124,
            back: 2,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 124,
            back: 7,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 124,
            back: 15,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 124,
            back: 16,
            group: 2,
            combo: 4,
            skip: 5,
        },
        TapData {
            offset: 125,
            back: 0,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 125,
            back: 1,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 125,
            back: 2,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 125,
            back: 7,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 125,
            back: 15,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 125,
            back: 16,
            group: 2,
            combo: 3,
            skip: 6,
        },
        TapData {
            offset: 126,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
        TapData {
            offset: 127,
            back: 0,
            group: 2,
            combo: 0,
            skip: 1,
        },
    ],
    combo_taps: &[
        0, 0, 1, 0, 1, 2, 3, 4, 68, 0, 1, 2, 7, 15, 16, 0, 2, 7, 15, 16,
    ],
    combo_begin: &[0, 1, 3, 9, 15, 20],
    group_begin: &[0, 16, 39, 643],
    combos_count: 5,
    reg_count: 163,
    tot_combo_backs: 20,
    group_names: &["accum", "code", "data"],
};
