#!/usr/bin/env bash

# From https://github.com/foundry-rs/foundry/blob/master/foundryup/install

set -eo pipefail

echo "Installing risc0up..."

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
RISC0_DIR=${RISC0_DIR-"$BASE_DIR/.risc0"}
RISC0_BIN_DIR="$RISC0_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/risc0/risc0/hmrtn/risc0up/risc0up/risc0up"
BIN_PATH="$RISC0_BIN_DIR/risc0up"

command -v curl >/dev/null 2>&1 || { echo >&2 "curl is required but it's not installed. Aborting."; exit 1; }

# Create the .risc0up bin directory and risc0up binary if it doesn't exist.
mkdir -p $RISC0_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

detect_shell() {
    case $SHELL in
    */zsh) PROFILE="${ZDOTDIR:-"$HOME"}/.zshenv"; PREF_SHELL='zsh' ;;
    */bash) PROFILE="$HOME/.bashrc"; PREF_SHELL='bash' ;;
    */fish) PROFILE="$HOME/.config/fish/config.fish"; PREF_SHELL='fish' ;;
    */ash) PROFILE="$HOME/.profile"; PREF_SHELL='ash' ;;
    *) echo "Could not detect shell, manually add ${RISC0_BIN_DIR} to your PATH." && exit 1 ;;
    esac
}

detect_shell


# add risc0up to PATH if it isn't already present
if [[ ":$PATH:" != *":${RISC0_BIN_DIR}:"* ]]; then
    echo "Adding risc0up to PATH in ${PROFILE}..."
    {
        echo
        echo "export PATH=\"\$PATH:$RISC0_BIN_DIR\""
    } >> "$PROFILE"
fi

echo "Detected your preferred shell as ${PREF_SHELL}."
echo "Added risc0up to PATH in ${PROFILE}."
echo "Run 'source ${PROFILE}' or start a new terminal session to use risc0up."
echo "Then, run 'risc0up' to install the zkVM."
