#!/usr/bin/env bash
# From https://github.com/foundry-rs/foundry/blob/master/foundryup/install

set -e

echo Installing risc0up...

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
RISC0_DIR=${RISC0_DIR-"$BASE_DIR/.risc0"}
RISC0_BIN_DIR="$RISC0_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/risc0/risc0/hmrtn/risc0up/risc0up/risc0up"
BIN_PATH="$RISC0_BIN_DIR/risc0up"

# Create the .risc0up bin directory and risc0up binary if it doesn't exist.
mkdir -p $RISC0_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

# Store the correct profile file (i.e. .profile for bash or .zshenv for ZSH).
case $SHELL in
*/zsh)
    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
    PREF_SHELL=zsh
    ;;
*/bash)
    PROFILE=$HOME/.bashrc
    PREF_SHELL=bash
    ;;
*/fish)
    PROFILE=$HOME/.config/fish/config.fish
    PREF_SHELL=fish
    ;;
*/ash)
    PROFILE=$HOME/.profile
    PREF_SHELL=ash
    ;;
*)
    echo "risc0up: could not detect shell, manually add ${RISC0_BIN_DIR} to your PATH."
    exit 1
esac

# Only add risc0up if it isn't already in PATH.
if [[ ":$PATH:" != *":${RISC0_BIN_DIR}:"* ]]; then
    # Add the risc0up directory to the path and ensure the old PATH variables remain.
    echo >> $PROFILE && echo "export PATH=\"\$PATH:$RISC0_BIN_DIR\"" >> $PROFILE
fi

echo && echo "Detected your preferred shell is ${PREF_SHELL} and added foundryup to PATH. Run 'source ${PROFILE}' or start a new terminal session to use risc0up."
echo "Then, simply run 'risc0up' to install the zkVM."
