// Copyright 2023 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

use clap::Parser;
use risc0_zkvm_fault::{FAULT_CHECKER_ELF, FAULT_CHECKER_ID};
#[derive(Parser)]
pub struct BootstrapFault;

impl BootstrapFault {
    pub fn run(&self) {
        let rust_code = format!(
            r##"// Copyright 2023 RISC Zero, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Warning: this code is generated by cargo xtask and should not be modified by
// hand.

/// The image ID of the fault checker guest program
#[rustfmt::skip]
pub const FAULT_CHECKER_ID: [u32; 8] = {FAULT_CHECKER_ID:?};

/// The ELF of the fault checker guest program
#[rustfmt::skip]
pub const FAULT_CHECKER_ELF: &[u8] = &{FAULT_CHECKER_ELF:?};
"##
        );

        std::fs::write("risc0/zkvm/src/fault_ids.rs", rust_code).unwrap();
    }
}
