workspace(name = "byz9")

load("@bazel_tools//tools/build_defs/repo:git.bzl", "git_repository")
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

http_archive(
    name = "bazel_skylib",
    sha256 = "74d544d96f4a5bb630d465ca8bbcfe231e3594e5aae57e1edbf17a6eb3ca2506",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.3.0/bazel-skylib-1.3.0.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.1.1/bazel-skylib-1.3.0.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()

http_archive(
    name = "com_google_googletest",
    sha256 = "ad7fdba11ea011c1d925b3289cf4af2c66a352e18d4c7264392fead75e919363",
    strip_prefix = "googletest-1.13.0",
    url = "https://github.com/google/googletest/archive/refs/tags/v1.13.0.tar.gz",
)

http_archive(
    name = "build_bazel_rules_apple",
    sha256 = "352428421c89dba8859055c3e1ba42f742c224544bf0e196c926d1cf44a2d726",
    url = "https://github.com/bazelbuild/rules_apple/releases/download/3.16.1/rules_apple.3.16.1.tar.gz",
)

load("@build_bazel_rules_apple//apple:repositories.bzl", "apple_rules_dependencies")

apple_rules_dependencies()

http_archive(
    name = "metal_cpp",
    build_file = "//bazel/third_party:metal_cpp.BUILD",
    sha256 = "0afd87ca851465191ae4e3980aa036c7e9e02fe32e7c760ac1a74244aae6023b",
    url = "https://developer.apple.com/metal/cpp/files/metal-cpp_macOS13.3_iOS16.4.zip",
)

load("//bazel/toolchain/risc0:repo.bzl", "risc0_toolchain")

risc0_toolchain(name = "risc0_toolchain")

load("//bazel/toolchain/rv32im-linux:repo.bzl", "rv32im_linux_toolchain")

rv32im_linux_toolchain(name = "rv32im_linux_toolchain")

http_archive(
    name = "riscv_tests",
    build_file = "//bazel/third_party:riscv_tests.BUILD",
    sha256 = "0c1a76d2d9600468893dddcf74a84b473ca7ac29e76678f488f3f67e318e845d",
    strip_prefix = "riscv-tests-b5ba87097c42aa41c56657e0ae049c2996e8d8d8",
    url = "https://github.com/riscv/riscv-tests/archive/b5ba87097c42aa41c56657e0ae049c2996e8d8d8.zip",
)

http_archive(
    name = "rules_cuda",
    sha256 = "e653b671a7311656f479f9793dc74174a56c11d677881b2924530daf02b3c5fd",
    strip_prefix = "rules_cuda-4f7fe962b41e1a9cd025a0864099e895191fb9ae",
    urls = ["https://github.com/bazel-contrib/rules_cuda/archive/4f7fe962b41e1a9cd025a0864099e895191fb9ae.tar.gz"],
)

load("@rules_cuda//cuda:repositories.bzl", "rules_cuda_dependencies", "rules_cuda_toolchains")

rules_cuda_dependencies()

rules_cuda_toolchains(register_toolchains = True)

new_local_repository(
    name = "risc0_sys",
    build_file = "//bazel/third_party:risc0_sys.BUILD",
    path = "../../../sys",
)

new_local_repository(
    name = "sppark",
    build_file = "//bazel/third_party:sppark.BUILD",
    path = "../../../../vendor/sppark",
)

# https://github.com/martinus/unordered_dense
new_local_repository(
    name = "unordered_dense",
    build_file = "//bazel/third_party:unordered_dense.BUILD",
    path = "../vendor/ankerl",
)

# https://github.com/983/Num
new_local_repository(
    name = "num",
    build_file = "//bazel/third_party:num.BUILD",
    path = "../vendor/num",
)

#
# Zirgen + MLIR
#

http_archive(
    name = "rules_python",
    sha256 = "954aa89b491be4a083304a2cb838019c8b8c3720a7abb9c4cb81ac7a24230cea",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.4.0/rules_python-0.4.0.tar.gz",
)

LLVM_COMMIT = "39df4945e1888d407777e58fbf03f6ad1e859c11"

LLVM_SHA256 = "3d0df55adab4ad225952f96508c1c47b206a61c9c07768a6644d2f09c15eae8f"

http_archive(
    name = "llvm-raw",
    build_file_content = "# empty",
    sha256 = LLVM_SHA256,
    strip_prefix = "llvm-project-" + LLVM_COMMIT,
    urls = ["https://github.com/llvm/llvm-project/archive/{commit}.tar.gz".format(commit = LLVM_COMMIT)],
)

load("@llvm-raw//utils/bazel:configure.bzl", "llvm_configure")

llvm_configure(name = "llvm-project")

maybe(
    http_archive,
    name = "llvm_zlib",
    build_file = "@llvm-raw//utils/bazel/third_party_build:zlib-ng.BUILD",
    sha256 = "e36bb346c00472a1f9ff2a0a4643e590a254be6379da7cddd9daeb9a7f296731",
    strip_prefix = "zlib-ng-2.0.7",
    urls = [
        "https://github.com/zlib-ng/zlib-ng/archive/refs/tags/2.0.7.zip",
    ],
)

maybe(
    http_archive,
    name = "llvm_zstd",
    build_file = "@llvm-raw//utils/bazel/third_party_build:zstd.BUILD",
    sha256 = "7c42d56fac126929a6a85dbc73ff1db2411d04f104fae9bdea51305663a83fd0",
    strip_prefix = "zstd-1.5.2",
    urls = [
        "https://github.com/facebook/zstd/releases/download/v1.5.2/zstd-1.5.2.tar.gz",
    ],
)

git_repository(
    name = "zirgen",
    commit = "9823fac68da2e95366f7a3a4caa02a0ebb6b59e2",
    remote = "https://github.com/risc0/zirgen.git",
)

http_archive(
    name = "rules_pkg",
    sha256 = "8f9ee2dc10c1ae514ee599a8b42ed99fa262b757058f65ad3c384289ff70c4b8",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_pkg/releases/download/0.9.1/rules_pkg-0.9.1.tar.gz",
        "https://github.com/bazelbuild/rules_pkg/releases/download/0.9.1/rules_pkg-0.9.1.tar.gz",
    ],
)

load("@rules_pkg//:deps.bzl", "rules_pkg_dependencies")

rules_pkg_dependencies()

CLANG_FORMAT_VERSION = "17.0.6"

http_archive(
    name = "clang-format-linux",
    build_file = "//bazel/third_party:clang-format.BUILD",
    strip_prefix = "clang+llvm-{}-x86_64-linux-gnu-ubuntu-22.04".format(CLANG_FORMAT_VERSION),
    urls = [
        "https://github.com/llvm/llvm-project/releases/download/llvmorg-{0}/clang+llvm-{0}-x86_64-linux-gnu-ubuntu-22.04.tar.xz".format(CLANG_FORMAT_VERSION),
    ],
)

http_archive(
    name = "clang-format-macos",
    build_file = "//bazel/third_party:clang-format.BUILD",
    strip_prefix = "clang+llvm-{}-arm64-apple-darwin22.0".format(CLANG_FORMAT_VERSION),
    urls = [
        "https://github.com/llvm/llvm-project/releases/download/llvmorg-{0}/clang+llvm-{0}-arm64-apple-darwin22.0.tar.xz".format(CLANG_FORMAT_VERSION),
    ],
)

BAZEL_CLANG_FORMAT_SHA256 = "f3f93a086ab2dcdfc8859e146b39a25c6653372c3f875797784f736d30bec18d"

http_archive(
    name = "bazel_clang_format",
    sha256 = BAZEL_CLANG_FORMAT_SHA256,
    strip_prefix = "bazel_clang_format-0.0.1",
    urls = ["https://github.com/oliverlee/bazel_clang_format/archive/refs/tags/0.0.1.tar.gz"],
)
