#!/usr/bin/env bash

# Adapted from https://github.com/foundry-rs/foundry/blob/master/foundryup/install

set -eo pipefail

clear

echo "💾 Installing rzup"

BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
RISC0_DIR=${RISC0_DIR-"$BASE_DIR/.risc0"}
RISC0_BIN_DIR="$RISC0_DIR/bin"

BIN_URL="https://raw.githubusercontent.com/risc0/risc0/main/rzup/install"
BIN_PATH="$RISC0_BIN_DIR/rzup"

command -v curl >/dev/null 2>&1 || { echo >&2 "curl is required but it's not installed. Aborting."; exit 1; }

# Create the .rzup bin directory and rzup binary if it doesn't exist.
mkdir -p $RISC0_BIN_DIR
curl -# -L $BIN_URL -o $BIN_PATH
chmod +x $BIN_PATH

detect_shell() {
    case $SHELL in
    */zsh) PROFILE="${ZDOTDIR:-"$HOME"}/.zshenv"; PREF_SHELL='zsh' ;;
    */bash) PROFILE="$HOME/.bashrc"; PREF_SHELL='bash' ;;
    */fish) PROFILE="$HOME/.config/fish/config.fish"; PREF_SHELL='fish' ;;
    */ash) PROFILE="$HOME/.profile"; PREF_SHELL='ash' ;;
    *) echo "Could not detect shell, manually add ${RISC0_BIN_DIR} to your PATH." && exit 1 ;;
    esac
}

detect_shell


# add rzup to PATH if it isn't already present
if [[ ":$PATH:" != *":${RISC0_BIN_DIR}:"* ]]; then
    echo "Adding rzup to PATH in ${PROFILE}..."
    {
        echo
        echo "export PATH=\"\$PATH:$RISC0_BIN_DIR\""
    } >> "$PROFILE"
fi

echo "Detected your preferred shell as ${PREF_SHELL}."
echo "Added rzup to PATH in ${PROFILE}."
echo "Run 'source ${PROFILE}' or start a new terminal session to use rzup."
echo "Then, run 'rzup' to install the zkVM."
