#!/usr/bin/env bash

VERSION=0.1.0

VERBOSE_MODE=1

print_banner() {
  echo "rzup v$VERSION"
  cat <<"EOF"

    ██████  █▀▀▀██
    ██████  █ ▄▀ █        Prove anything.
    ██████  ██▄▄▄█       Verify everywhere.
    ██████
    ██████   RISC
    ██████   ZERO

Contribute      : https://github.com/risc0/
Documentation   : https://dev.risczero.com/
Chat & Support  : https://discord.com/invite/risczero/

EOF
}

log_verbose() {
  if [ "$VERBOSE_MODE" -eq 0 ]; then
    echo "$@"
  fi
}

execute_with_feedback() {
  local COMMAND="$1"
  local MESSAGE="$2"

  echo "$MESSAGE..."

  if [ "$VERBOSE_MODE" -eq 0 ]; then
    echo "Executing: $COMMAND"
    eval "$COMMAND"
    local STATUS=$?
    if [ $STATUS -ne 0 ]; then
      echo "Error executing command: $COMMAND"
      exit $STATUS
    fi
  else
    eval "$COMMAND" >/dev/null 2>&1 &
    pid=$!
    local spinstr='|/-\'
    while kill -0 $pid 2>/dev/null; do
      local temp=${spinstr#?}
      printf " [%c]  " "$spinstr"
      local spinstr=$temp${spinstr%"$temp"}
      sleep 0.1
      printf "\b\b\b\b\b\b"
    done
    wait $pid
    local STATUS=$?
    if [ $STATUS -ne 0 ]; then
      echo "Error executing command: $COMMAND"
      exit $STATUS
    fi
  fi
}

check_rust_installed() {
  if ! command -v rustc &>/dev/null; then
    echo "Rust is not installed. Please install Rust using https://rustup.rs/ and rerun this script."
    exit 1
  fi
}

install_cargo_binstall() {
  execute_with_feedback "cargo install --locked cargo-binstall --quiet" "Installing cargo-binstall"
}

binstall_cargo_risczero() {
  if [ -n "$RISCZERO_VERSION" ]; then
    execute_with_feedback "cargo binstall cargo-risczero@$RISCZERO_VERSION --no-confirm" "Installing cargo-risczero version $RISCZERO_VERSION"
  else
    execute_with_feedback "cargo binstall cargo-risczero --no-confirm" "Installing the latest version of cargo-risczero"
  fi
}

install_risczero() {
  execute_with_feedback "cargo risczero install" "Installing the risc0 toolchain"
}

usage() {
  cat 1>&2 <<EOF
The installer for RISC Zero.

Install, update or revert to a specific RISC Zero version.

USAGE:
    rzup <OPTIONS>

OPTIONS:
    -h, --help      Print help information
    -v, --version   Install a specific version of cargo-risczero
    --verbose       Enable verbose output
EOF
}

parse_args() {
  while [[ "$#" -gt 0 ]]; do
    case $1 in
    -v | --version)
      RISCZERO_VERSION="$2"
      shift 2
      ;;
    --verbose)
      VERBOSE_MODE=$((1 - VERBOSE_MODE))
      shift
      ;;
    -h | --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      exit 1
      ;;
    esac
  done
}

main() {
  parse_args "$@"
  print_banner
  check_rust_installed
  install_cargo_binstall
  binstall_cargo_risczero
  install_risczero

  echo "Installation complete. Run cargo risczero --help to get started."
}

main "$@"
